version: '3.8'

services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    env_file:
      - ./localEnv/mongodb.env

  user:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - 80:3000
    env_file:
      - ./localEnv/user-service.env
    depends_on:
      - mongodb

volumes:
  mongodb_data: